#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : more-itertools
Version  : 8.6.0
Release  : 36
URL      : https://files.pythonhosted.org/packages/b0/0f/da7bf94283720a148fe4d7335c8b74b67c8e978c6498487d699a0d86c72b/more-itertools-8.6.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/b0/0f/da7bf94283720a148fe4d7335c8b74b67c8e978c6498487d699a0d86c72b/more-itertools-8.6.0.tar.gz
Summary  : More routines for operating on iterables, beyond itertools
Group    : Development/Tools
License  : MIT
Requires: more-itertools-license = %{version}-%{release}
Requires: more-itertools-python = %{version}-%{release}
Requires: more-itertools-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
More Itertools
        ==============

%package license
Summary: license components for the more-itertools package.
Group: Default

%description license
license components for the more-itertools package.


%package python
Summary: python components for the more-itertools package.
Group: Default
Requires: more-itertools-python3 = %{version}-%{release}

%description python
python components for the more-itertools package.


%package python3
Summary: python3 components for the more-itertools package.
Group: Default
Requires: python3-core
Provides: pypi(more_itertools)

%description python3
python3 components for the more-itertools package.


%prep
%setup -q -n more-itertools-8.6.0
cd %{_builddir}/more-itertools-8.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604335835
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/more-itertools
cp %{_builddir}/more-itertools-8.6.0/LICENSE %{buildroot}/usr/share/package-licenses/more-itertools/0d43a836dac65c0ea426ad49c881a1086600bf85
cp %{_builddir}/more-itertools-8.6.0/docs/license.rst %{buildroot}/usr/share/package-licenses/more-itertools/ff8a160b2ccafe5031612c084dfcd3cc95950414
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/more-itertools/0d43a836dac65c0ea426ad49c881a1086600bf85
/usr/share/package-licenses/more-itertools/ff8a160b2ccafe5031612c084dfcd3cc95950414

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
